[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
legion = "=0.3.1"

[profile.legion-old]
inherits = "dev"
opt-level = 1

[profile.legion-old.package."*"]
opt-level = 3

