[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_ecs = "0.13.2"
bevy_derive = "0.13.2"

[dependencies.bracket-lib]
git = "https://github.com/XReaper95/bracket-lib.git"
branch = "bevy_ecs_fix"
features = ["default", "bevy"]
